spring:
  application:
    name: router-zuul
  profiles:
    active:
    - common
    - eureka
server:
  port: 8080
  
zuul:
  retryable: false
  routes:
    api-register:
      path: /register/**
      service-id: register-center
    api-user:
      path: /user/**
      service-id: fin-user