logging:
  level:
    root: info
spring:
  application:
    name: common-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: x5
server:
  port: 80
mapper:
  location: classpath*:/mapper/*.xml
fastjson:
  dateFormat: yyyy-MM-dd HH:mm:ss